[package]
name = "mtls-sidecar"
version = "0.1.0"
edition = "2021"

[lib]
name = "mtls_sidecar"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
rustls = "0.23"
rustls-pemfile = "2.1"
tokio-rustls = "0.26"
hyper = { version = "1.7", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
hyper-rustls = "0.27"
http-body-util = "0.1"
bytes = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = "1.0"
x509-parser = "0.16"
notify = "8.2"
axum = { version = "0.8", features = ["tokio"] }
prometheus = "0.14"
lazy_static = "1.4"
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.23"
rcgen = "0.13"
time = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
async-trait = "0.1"
portpicker = "0.1"

[profile.release]
lto = true
codegen-units = 1