[package]
name = "mtls-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
rustls = "0.23"
rustls-pemfile = "2.1"
tokio-rustls = "0.26"
hyper = { version = "1.7", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
hyper-rustls = "0.27"
http-body-util = "0.1"
bytes = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = "1.0"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.23"
rcgen = "0.13"
time = "0.3"

[profile.release]
lto = true
codegen-units = 1