apiVersion: v1
kind: Pod
metadata:
  name: mtls-test-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    args:
    - |
        while true; do
          curl -D- --retry 5 --retry-delay 1 http://mtls-sidecar-demo.default.svc.cluster.local/
          sleep 5
        done
    env:
      - name: ALL_PROXY
        value: http://localhost:3128
    volumeMounts:
    - name: trust-bundle
      mountPath: /etc/ssl/certs
      readOnly: true
  - name: mtls-sidecar
    image: sebcvm/mtls-sidecar
    env:
      - name: RUST_LOG
        value: debug
      - name: TLS_LISTEN_PORT
        value: ""
      - name: OUTBOUND_PROXY_PORT
        value: "3128"
    volumeMounts:
      - name: trust-bundle
        mountPath: /etc/ca
        readOnly: true
      - name: client-certs
        mountPath: /etc/client-certs
        readOnly: true
  volumes:
  - name: trust-bundle
    configMap:
      defaultMode: 420
      name: testing-trust-bundle
      optional: false
  - name: client-certs
    csi:
      driver: csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        csi.cert-manager.io/issuer-name: testing-issuer
        csi.cert-manager.io/issuer-kind: ClusterIssuer
        csi.cert-manager.io/dns-names: "${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local"
        csi.cert-manager.io/fs-group: "102"
