apiVersion: v1
kind: Pod
metadata:
  name: mtls-test-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    args:
    - |
      id && \
      ls -al /etc/ssl && \
      ls -al /etc/ssl/certs && \
      ls -al /etc/ssl/client && \
      curl -D- \
        --cacert /etc/ssl/certs/ca-bundle.crt \
        --cert /etc/ssl/client/tls.crt \
        --key /etc/ssl/client/tls.key \
        https://mtls-sidecar-demo.default.svc.cluster.local/
    volumeMounts:
    - name: trust-bundle
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: client-certs
      mountPath: /etc/ssl/client
      readOnly: true
  volumes:
  - name: trust-bundle
    configMap:
      defaultMode: 420
      name: testing-trust-bundle
      optional: false
  - name: client-certs
    csi:
      driver: csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        csi.cert-manager.io/issuer-name: testing-issuer
        csi.cert-manager.io/issuer-kind: ClusterIssuer
        csi.cert-manager.io/dns-names: "${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local"
        csi.cert-manager.io/fs-group: "102"
